### ISSUE TITLE
Wrong link in the "New Update Available" message

### ISSUE THREAD

**Issue by Monotek18** [kwsch/PKHeX#1382]
The message redirect to:
https://projectpokemon.org/PKHeX/
But there is nothing here.

https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/MainWindow/Main.cs#L91

it should be: 
https://projectpokemon.org/pkhex/
instead of:
https://projectpokemon.org/PKHeX/

**Comment by kwsch** [comment]
Should be fixed on the website instead...
@evandixon

**Comment by sora10pls** [comment]
As a heads up with the 09/05/2017 release, this bug still exists.
![image](https://user-images.githubusercontent.com/17801814/30068936-454f0d42-922d-11e7-87bd-8700340412bf.png)

**Comment by kwsch** [comment]
@evandixon

**Comment by kwsch** [comment]
More or less an alteration to the community website that changed the link, not so much a PKHeX bug ;)
