### ISSUE TITLE
Some Pokemon flagged as Illegal

### ISSUE THREAD

**Issue by x7l7j8cc** [kwsch/PKHeX#3626]
Hi, as title suggest, i have some pokemon showing Illegal Flags, but all this pokemon have been Captured in game Legally.
I spent hours/days on getting all pokemons and evolving them. 

The pokemon with problems are:
- Combee: Unable to Match Encounter from Origin Game.
- Happiny: Invalid Marking (Dawn Mark) ???
- Dudunsparce: Unable to Match Encounter from Origin Game.
- Stantler: Form Argument is not Allowed for this Encounter ?????
- Gothorita: Unable to Match Encounter from Origin Game.
- and Baxcalibur: Invalid Move(3) "Icicle Crash" and Unable to Match Encounter from Origin Game.

I dont know what happened, really.

**Comment by Lusamine** [comment]
Please redownload the program (will fix Stantler) and provide the files for the ones that are still illegal. Many issues are known but it helps to have examples.

**Comment by kwsch** [comment]
For other readers, here's what we know is deficient:
1. Weather/Time of Day marks
2. Crossover encounters (encounters that walk from one location to another)
3. New Eevee distribution raid encounters
4. Form changing pokemon (like Oricorio) not matching the expected tera type

**Comment by x7l7j8cc** [comment]
Downloaded and ReChecked... Still this pokemon have problems... 

- Combee: Unable to Match Encounter from Origin Game.
- Happiny: Invalid Marking (Dawn Mark) ???
- Dudunsparce: Unable to Match Encounter from Origin Game.
- Gothorita: Unable to Match Encounter from Origin Game.
- and Baxcalibur: Invalid Move(3) "Icicle Crash" and Unable to Match Encounter from Origin Game.

Dont know if this help, but:
- Combee: Found in "Ruchbah Squad’s Base" at Lvl45
- Happiny: "South Province (Area One)" at Lvl6
- Dudunsparce: Evolved from Dunsparce, captured from "Dalizapa Passage" Lvl16
- Gothorita: "Alfornada" Lvl39
- and Baxcalibur: Evolved from Frigibax, captured from "Dalizapa Passage" Lvl16

Sincerely, i dont know what happened.

**Comment by Lusamine** [comment]
Please zip up the files and attach them here.

**Comment by x7l7j8cc** [comment]
Of the PKM files?

**Comment by howdy-im-david** [comment]
Not sure if needing another thread but here's mine from pulling up my current save.
[pk9_issues.zip](https://github.com/kwsch/PKHeX/files/10088213/pk9_issues.zip)

**Comment by howdy-im-david** [comment]
Apologies, one that I missed that flagged for "Invalid Marking: Uncommon Mark"
[1009 - Clodsire.zip](https://github.com/kwsch/PKHeX/files/10088250/1009.-.Clodsire.zip)

**Comment by Galarian-Corsola** [comment]
Found an incorrect illegal issue with the rotom forms. Since they have ghost as one of their possible original tera types, it's marked as illegal when it changes form due to losing its ghost type.

**Comment by luckystarwy** [comment]
Bisharp and Primeape just like Stantler. Form Argument is not Allowed for this Encounter

**Comment by Lusamine** [comment]
> Found an incorrect illegal issue with the rotom forms. Since they have ghost as one of their possible original tera types, it's marked as illegal when it changes form due to losing its ghost type.
Please upload example files for us to look at to fix the error.


> Bisharp and Primeape just like Stantler. Form Argument is not Allowed for this Encounter
Re-download the program and if they are still flagging, provide the example files.

**Comment by Araraura** [comment]
Apologies if this isn't the right way to report legality issues, but I've got some pokemon that are also flagged as illegal for some reason:
[Illegals.zip](https://github.com/kwsch/PKHeX/files/10089895/Illegals.zip)

**Comment by Galarian-Corsola** [comment]
Here's the rotom
[479-03 - Rotom.zip](https://github.com/kwsch/PKHeX/files/10094563/479-03.-.Rotom.zip)

**Comment by Ritaku02** [comment]
I also have a legit-caught, unaltered pokemon that's flagged as illegal. I'm currently at work, but I'll zip the pkm and upload it here after I get home.

**Comment by joeymavity** [comment]
This is a legit hoppip with flag "Invalid: Invalid Marking: Dawn Mark". I changed OT info only
[661 - Fletchling - E2C8AC6B996F.zip](https://github.com/kwsch/PKHeX/files/10095183/661.-.Fletchling.-.E2C8AC6B996F.zip)

**Comment by InkDragon** [comment]
Similar issue, these are all legit caught or bred. Rotoms are throwing errors because their tera type is that of their base form(ghost) but not of their current form(fire/flying/ect). 

[errorpk9.zip](https://github.com/kwsch/PKHeX/files/10095274/errorpk9.zip)

**Comment by FauxBlue** [comment]
Just got one in my save so far. Caught it early on, put in the box, haven't thought about it since, didn't modify it.
"Invalid: Unable to match an encounter from origin game."
Yungoos caught at Inlet Grotto.
[734 - Ol' Goose - 4F0C05E611C2.zip](https://github.com/kwsch/PKHeX/files/10095299/734.-.Ol.Goose.-.4F0C05E611C2.zip)

**Comment by InkDragon** [comment]
here are three more, one of which is wild tera type psyschic own tempo rockruff with zen headbutt(flags this move)

[moarerrors.zip](https://github.com/kwsch/PKHeX/files/10095406/moarerrors.zip)

**Comment by Ninjistix** [comment]
[174 - Igglybuff - 428EDA1C8A2E.zip](https://github.com/kwsch/PKHeX/files/10096358/174.-.Igglybuff.-.428EDA1C8A2E.zip)
[734 - Yungoos - 2B2317FAA78F.zip](https://github.com/kwsch/PKHeX/files/10096359/734.-.Yungoos.-.2B2317FAA78F.zip)
[734 - Yungoos - 3C3E98287039.zip](https://github.com/kwsch/PKHeX/files/10096360/734.-.Yungoos.-.3C3E98287039.zip)
here's some I came across.

**Comment by Lusamine** [comment]
I'm currently saving these; thanks to everyone for the contributions!

For any further posts, please check that your Pokemon is still illegal on the development build. Many issues have been fixed already.

https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

**Comment by Ritaku02** [comment]
> Just got one in my save so far. Caught it early on, put in the box, haven't thought about it since, didn't modify it. "Invalid: Unable to match an encounter from origin game." Yungoos caught at Inlet Grotto. [734 - Ol' Goose - 4F0C05E611C2.zip](https://github.com/kwsch/PKHeX/files/10095299/734.-.Ol.Goose.-.4F0C05E611C2.zip)

That's actually the same Pokemon I was gonna report! Guess I don't need to, now :)

**Comment by BDERT666** [comment]
[mons.zip](https://github.com/kwsch/PKHeX/files/10096668/mons.zip)

Added a couple of mine here too that are still showing as illegal on the last development build.

**Comment by agpor** [comment]
I think all mons from 6 star raids (lvl 75) are all flagged as Illegal.
Example: https://gyazo.com/04d50896ddbeab445fbdcc213f8cc01e

**Comment by Lusamine** [comment]
> I think all mons from 6 star raids (lvl 75) are all flagged as Illegal. Example: https://gyazo.com/04d50896ddbeab445fbdcc213f8cc01e

This doesn't show anything flagging illegal in PKHeX, and mine are not illegal on the latest development build.  Please provide a Pokemon file if yours are illegal.

**Comment by agpor** [comment]
> > I think all mons from 6 star raids (lvl 75) are all flagged as Illegal. Example: https://gyazo.com/04d50896ddbeab445fbdcc213f8cc01e
> 
> This doesn't show anything flagging illegal in PKHeX, and mine are not illegal on the latest development build. Please provide a legitimate, unmodified Pokemon file if yours are illegal.

Sorry I just guessed because I tried to replicate that mon but maybe the PIDs have different formula for raid mons? Tried to PID reroll other legitimate mons I have and got same alert ("Invalid: Unable to match and encounter from origin game")

**Comment by Lusamine** [comment]
> > > I think all mons from 6 star raids (lvl 75) are all flagged as Illegal. Example: https://gyazo.com/04d50896ddbeab445fbdcc213f8cc01e
> > 
> > 
> > This doesn't show anything flagging illegal in PKHeX, and mine are not illegal on the latest development build. Please provide a legitimate, unmodified Pokemon file if yours are illegal.
> 
> Sorry I just guessed because I tried to replicate that mon but maybe the PIDs have different formula for raid mons? Tried to PID reroll other legitimate mons I have and got same alert ("Invalid: Unable to match and encounter from origin game")

This is a thread for reporting legitimate, unmodified, original data that is incorrectly flagging illegal. It is not for assistance fabricating data. Modifying raid Pokémon will cause them to become illegal. This is not an error in the program.

**Comment by edo9300** [comment]
I also got some pokemons incorrectly flagged as illegal, all of them give the error ``Unable to Match Encounter from Origin Game``, except for Sableye that instead gives an ``invalid marking`` error
[invalid pokemons.zip](https://github.com/kwsch/PKHeX/files/10098048/invalid.pokemons.zip)

**Comment by Ritaku02** [comment]
Pokemon, legitimately caught, still flagged as illegal on latest dev build
[Scarlet - Violet.zip](https://github.com/kwsch/PKHeX/files/10098769/Scarlet.-.Violet.zip)

**Comment by jusitnboggs** [comment]
[734 - Yungoos - 65D7C901C2D3.zip](https://github.com/kwsch/PKHeX/files/10099362/734.-.Yungoos.-.65D7C901C2D3.zip)
Your update has fixed all but this one.

**Comment by imeangay** [comment]
Hello your dev update fixed a lot of my Eevee's but these are still illegal, Origin game not verified
[Illegal pokemon.zip](https://github.com/kwsch/PKHeX/files/10109512/Illegal.pokemon.zip)

**Comment by sudot0ph** [comment]
Got a few more false positives. All caught in raid battles.

[Illegal Terra forms.zip](https://github.com/kwsch/PKHeX/files/10109578/Illegal.Terra.forms.zip)

**Comment by Lusamine** [comment]
> Got a few more false positives. All caught in raid battles.
> 
> [Illegal Terra forms.zip](https://github.com/kwsch/PKHeX/files/10109578/Illegal.Terra.forms.zip)

These are all hacked with 6 IVs.
![image](https://user-images.githubusercontent.com/30205550/204434632-da2d54d7-e8ac-4cb0-ba32-2afbf9a88c66.png)

Please do not post flagged Tera Raids that are affected by cheat codes or from unknown sources online. They are appropriately flagged.

**Comment by Dylan-Brotherston** [comment]
illegal Yungoos from Inlet Grotto:
[734 - Yungoos - 87E69BF288C3.zip](https://github.com/kwsch/PKHeX/files/10123276/734.-.Yungoos.-.87E69BF288C3.zip)
Tested on the most recent dev build.

**Comment by Ninjistix** [comment]
[Scarlet.zip](https://github.com/kwsch/PKHeX/files/10147668/Scarlet.zip)
Just went to sort my box, and found these 8 flagged as invalid with the latest Dev build

**Comment by imeangay** [comment]
The pokemon I posted a few posts up are still invalid as the latest Dev build marked as unable to match ecounters.

I was curious though, is this issue will flag my game somehow if i edit EV's of pokemon and then reimport my save?
I haven't personally done anything with the tool as I'm worried about the pokemon that are flagged by the tool that will somehow ruin the save, (paranoid cx all good if you can't answer for any reason, much respect for your work!)

**Comment by Lusamine** [comment]
> The pokemon I posted a few posts up are still invalid as the latest Dev build marked as unable to match ecounters.
> 
> I was curious though, is this issue will flag my game somehow if i edit EV's of pokemon and then reimport my save? I haven't personally done anything with the tool as I'm worried about the pokemon that are flagged by the tool that will somehow ruin the save, (paranoid cx all good if you can't answer for any reason, much respect for your work!)

Please do not use this thread to ask about ban risks and penalties. Open a [Discussion](https://github.com/kwsch/PKHeX/discussions) if you need to do that.

**Comment by Galarian-Corsola** [comment]
[585-01-Deerling.zip](https://github.com/kwsch/PKHeX/files/10149193/585-01-Deerling.zip)
Deerling found right outside the Schedar Base that marks as illegal

**Comment by nonamethanks** [comment]
[pkm.zip](https://github.com/kwsch/PKHeX/files/10149355/pkm.zip)
Both of these are flagged as invalid in latest dev build. Bronzong was caught in an outbreak using sandwich encounter modifier

**Comment by nonamethanks** [comment]
[0053 - Persian - 2690992941.zip](https://github.com/kwsch/PKHeX/files/10164134/0053.-.Persian.-.2690992941.zip) Unable to match location + invalid mark
This pokemon actually entered a city, which surprised me a lot because I thought they despawned when you got near those. He walked right in and started following a road like other NPC.

**Comment by Maxcension** [comment]
[pokemon violet 101.zip](https://github.com/kwsch/PKHeX/files/10178293/pokemon.violet.101.zip)

4 of my pokémons flagged as invalid in latest dev build! :)

**Comment by BtEtta** [comment]
Throwing up all the flagged pokémon I've picked up so far. Most are "unable to match an encounter" with a couple of "Invalid marking".
[Encounter.zip](https://github.com/kwsch/PKHeX/files/10181359/Encounter.zip)
[Invalid Mark.zip](https://github.com/kwsch/PKHeX/files/10181361/Invalid.Mark.zip)
All checked on latest build.

**Comment by BtEtta** [comment]
Commit https://github.com/kwsch/PKHeX/commit/89b10aec7e1d798c02b9adf9c8c8795da3ec3673 broke validity on a lot of pokémon in my boxes.
[Broken.zip](https://github.com/kwsch/PKHeX/files/10195163/Broken.zip)

**Comment by max-m** [comment]
Both Pokémon are flagged for being “Unable to match encounter from origin game” in stable and the Development Build 22.12.2+26.
Both were caught while on version 1.0.1.
[invalid_encounters.zip](https://github.com/kwsch/PKHeX/files/10198917/invalid_encounters.zip)

The Staravia was caught in this area:
![staravia](https://user-images.githubusercontent.com/642457/206821056-44d9ac2f-0c81-4343-a2f6-24942d438acd.jpg)
![2022112217094600-1A552196CBAEC7F073BF13D42EA6C787](https://user-images.githubusercontent.com/642457/206821064-b32e4643-4585-4acd-9974-d79738ef956f.jpg)

As to the Corviknight, no idea where exactly.

**Comment by Lusamine** [comment]
> Commit [89b10ae](https://github.com/kwsch/PKHeX/commit/89b10aec7e1d798c02b9adf9c8c8795da3ec3673) broke validity on a lot of pokémon in my boxes. [Broken.zip](https://github.com/kwsch/PKHeX/files/10195163/Broken.zip)

This should be fixed on latest commit.

**Comment by kwsch** [comment]
With the latest commit, most of these have been resolved. Only issues remaining are the Inlet Grotto and Dalizapa Passage (tunnel) coordinate checks.

**Comment by Ninjistix** [comment]
[Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip)
As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal. 

![image](https://user-images.githubusercontent.com/12572974/206886026-892bbcb1-d785-4f4e-b775-bfbddd744b22.png)
![image](https://user-images.githubusercontent.com/12572974/206886043-b66e86e1-1ee9-40e3-935f-4edd6877b3d3.png)

**Comment by Lusamine** [comment]
> [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.

Are the crystal cavern Pokemon from your own game, or did you join another person's raid?

**Comment by Ninjistix** [comment]
> > [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.
> 
> Are the crystal cavern Pokemon from your own game, or did you join another person's raid?

my own game.

**Comment by Lusamine** [comment]
> > > [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.
> > 
> > 
> > Are the crystal cavern Pokemon from your own game, or did you join another person's raid?
> 
> my own game.

Did you have cheats of any sort running?

**Comment by Ninjistix** [comment]
> > > > [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.
> > > 
> > > 
> > > Are the crystal cavern Pokemon from your own game, or did you join another person's raid?
> > 
> > 
> > my own game.
> 
> Did you have cheats of any sort running?

Restore Tera Orb after battle and 100% Catch

**Comment by Lusamine** [comment]
> > > > > [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.
> > > > 
> > > > 
> > > > Are the crystal cavern Pokemon from your own game, or did you join another person's raid?
> > > 
> > > 
> > > my own game.
> > 
> > 
> > Did you have cheats of any sort running?
> 
> Restore Tera Orb after battle and 100% Catch

The Pokemon looks to be affected by cheat codes. Please only submit Pokemon from an unmodded, personal game.

**Comment by Ninjistix** [comment]
> > > > > > [Scarlet.zip](https://github.com/kwsch/PKHeX/files/10201464/Scarlet.zip) As of the latest commit these are still flagged as illegal, the two Yungoos were encountered in that cave [Inlet Grotto] where you are attacked by the Houndoom, the diglet I caught there is marked as Legal.
> > > > > 
> > > > > 
> > > > > Are the crystal cavern Pokemon from your own game, or did you join another person's raid?
> > > > 
> > > > 
> > > > my own game.
> > > 
> > > 
> > > Did you have cheats of any sort running?
> > 
> > 
> > Restore Tera Orb after battle and 100% Catch
> 
> The Pokemon looks to be affected by cheat codes. Please only submit Pokemon from an unmodded, personal game.

okay, will do

**Comment by javierhimura** [comment]
The following 2 legit pokemon have illegal invalid marking, even with the changes of the latest commits.
I also include a third Chinese Grimmer I receive with wonder trade with Illegal Marking: Cloudy Mark. I can confirm its legitimacy but given it is just a low level Grimmer with nothing special, I don't think why it would be hacked.
I also add my legit Inlet Grotto Yungoos, which has already been reported.

[Invalid Marking.zip](https://github.com/kwsch/PKHeX/files/10202147/Invalid.Marking.zip)

**Comment by Lusamine** [comment]
> The following two legit pokemon have illegal invalid marking, even with the changes of the latest commits. I also include a third Chinese Grimmer I receive with wonder trade with Illegal Marking: Cloudy Mark. I can't confirm its legitimacy, but given it is just a low-level Grimmer with nothing special, I don't think why it would be hacked. I also add my legit Inlet Grotto Yungoos, which has already been reported.
> 
> [Invalid Marking.zip](https://github.com/kwsch/PKHeX/files/10202147/Invalid.Marking.zip)

All of these are legal for me on latest commit except Yungoos, which is known since everyone's Inlet Grotto Yungoos is flagged.

**Comment by CyraFen** [comment]
not sure if crossover encounters have been fixed yet but I have another to add, tested on the latest commit:
[149 - Dragonite - F81B1267B6BD.zip](https://github.com/kwsch/PKHeX/files/10249769/149.-.Dragonite.-.F81B1267B6BD.zip)
crossed from north province 2 to north province 1

**Comment by kwsch** [comment]
Closing, all data reported in this issue that is truly legal is now correctly identified as legal.

Thank you for the reports~!
