### ISSUE TITLE
Editing inventory sets every item as new.

### ISSUE THREAD

**Issue by BtEtta** [kwsch/PKHeX#3639]
**Describe the bug**
Opening the inventory editor then closing it with the save button sets the 'new' flag for every item. Even if nothing was actually edited.

**To Reproduce**
1. Open the inventory editor
2. Close the editor by clicking "Save"
3. Reopen the inventory editor
4. Every item will now have its 'new' flag ticked

**Expected behavior**
Each item's 'new' flag should be preserved as it was shown in the editor prior to clicking "Save"

**Additional context**
I have confirmed that this is not just a visual bug in PKHeX, restoring an edited file with this problem to my game results in every item having the 'new' flag.

**Comment by Lusamine** [comment]
Should be fixed on Development Build (latest commit).
Please check all errors on Dev Build prior to reporting.
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

**Comment by BtEtta** [comment]
The error still exists on the latest dev build.
I also compiled a version from the latest source for good measure and no difference.

**Comment by Lusamine** [comment]
https://github.com/kwsch/PKHeX/commit/f1b8992989b18f7c570877fae5688d1c4baf72c4

See if this fixed it.

**Comment by BtEtta** [comment]
Yup, that seems to have done the trick.
