### ISSUE TITLE
Festival Coins issue with latest commit

### ISSUE THREAD

**Issue by TCJJ** [kwsch/PKHeX#475]
I just updated from the public release build from Friday to the latest commit (compiled myself on Windows 10 - I did that multiple times last week and it was fine).

Festival Coins are now editable, of course, but I had almost 9,999,999 (maxed out with NTR cheats, then I spent some) and PKHeX only showed 9,999. I decided to make it 10 coins so that it looked legitimate again, but doing so seems to have corrupted my save as I can no longer inject it properly.

Reverting back to the latest public release of PKHeX no longer has the Festival Coins option, and saving with this version doesn't seem to fix the problem (I didn't back up beforehand because I haven't had a problem over the last week so I got complacent).

The only other change I made was to my Mimikyu to change its nature, EVs, IVs and moves, but it's completely legal, so the discrepancy with the Festival Coins seems to be the issue.

For the record, I started on a digital Moon, then transferred to digital Sun, then transferred to my physical Sun when it arrived today. The save worked fine before this round of editing, even on the cartridge. No amounts of deleting data and reinfecting will get my save working again, so I'm convinced the Festival Coin editing is the culprit.

**Comment by fadeZero** [comment]
i have tried adding a 1000 festival coins. when i get at least 1 Festival coin it becomes 1001, as expected, but when i talk to a shop and try to buy something i see the old amount (32 festival coins), not 1001. But again, when i talk to someone i still have 1001...as there are different slots of festival coins

**Comment by kamuisama** [comment]
I think it's the total Festival Coins that you have collected not what's left. That's why your festival plaza can level up straight away just by getting 1 FC if you set it to 9999 or max numbers.

**Comment by kwsch** [comment]
Fixed the Trainer Editor setting maximum from using the BP's maximum value :)
Setting 9,999,999 should be possible now.

**Comment by TCJJ** [comment]
Hmm, Festival Coins are fine now - they can be maxed out at 9,999,999 as you said - but my save still shows up as corrupted.

Furthermore, if I wipe the save on the cartridge and start a new game, that new save won't open in PKHeX either.

Festival Coins aside, the only other thing I can think of that is different to normal is that I acquired my Game Sync ID between the working and corrupted saves (working save w/game sync ID>exported and edited with PKHeX>imported but now corrupt), and PKHeX shows no Game Sync ID, so maybe that's the problem?

In case it's of any use for potentially fixing other bugs (or even just recovering my save file), I've attached the two aforementioned files.

[main files.zip](https://github.com/kwsch/PKHeX/files/610870/main.files.zip)

**Comment by MysticZangetsu** [comment]
I have found with going between cart and digital copies it goes from digital to cart fine but when coming back it would seem broken then I deleted the secure value just for kicks and it worked so when coming from cart to digital try deleting the secure value afterward should work.

**Comment by TCJJ** [comment]
SecureValue is irrelevant though because JKSM automatically deletes it and the cartridge doesn't have a SecureValue. As I said, I already transferred successfully from digital to cartridge, but now I can't import my edited save back into the cartridge. I haven't used the digital version since I exported my save from it and had it successfully working on the cartridge.

**Comment by Marctastikk** [comment]
Festival coins still not adding up in the shop.

**Comment by kwsch** [comment]
Anyone still having issues with the latest commit?

**Comment by noakei** [comment]
Still adding up the total coins only and not the owned ones

**Comment by noakei** [comment]
now it works
