### ISSUE TITLE
Legal Pokemon Showing up as Illegal in the Database Search

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#844]
Hoopa Unbound, and Dandy Furfrou are both showing up as illegal in the database. Although when I view them they have the green legality check mark. Viewing and setting them does not fix this issue.

Thanks for reading.

**Comment by Arch9SK7** [comment]
Because the database is showing he dumped pk7 files. After you set them with the green checkmark you just re dump the database and you'll see it is fixed.

**Comment by greenDarkness** [comment]
I don't have any dumped pk7 files in the database, and I also have it said to only load from the boxes. Even so, I dumped my boxes, re-ran the database, and this issue still persists.

**Comment by Arch9SK7** [comment]
Well they dump to the same directory as PKHeX.exe In a folder called "pkmndb" find that and delete all the PK7 files in there then dump again.

**Comment by greenDarkness** [comment]
I did that, and the database still says that Hoopa Unbound, and Dandy Furfrou aren't legal even though they have the green check mark.

**Comment by Arch9SK7** [comment]
That is really odd...

**Comment by Mrtops** [comment]
It is probably just a place where we didn't remember to have it check to see if it is legal and is automatically showing it as illegal

**Comment by greenDarkness** [comment]
Would it help if I uploaded the pk7 files?

**Comment by kwsch** [comment]
Legality checks were recently added for formes that cannot exist inside the box.

>Hoopa Unbound
>Dandy Furfrou 

:)

**Comment by greenDarkness** [comment]
So, does that mean Hoopa Unbound, and Dandy Furfrou cannot exist inside the box? 

Thanks for the response by the way. ^_^

**Comment by kwsch** [comment]
Correct!
Refer to https://github.com/kwsch/PKHeX/issues/806.

**Comment by greenDarkness** [comment]
Thanks!
